apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/open-telemetry/opentelemetry-operator.git
    targetRevision: v0.147.0
    path: config/default

  destination:
    server: https://kubernetes.default.svc
    namespace: otel

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
