apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omkarsingad/modules.git
    targetRevision: main
    path: opentelemetry/chart/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: observability   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
