apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator
    path: example/prometheus-operator-crd
    targetRevision: v0.90.1   # pin version (IMPORTANT)

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - Replace=true
      - ServerSideApply=true
